---
# Install needed roles from Ansible Galaxy

- src: coglinev3.ansible_python
  version: master
  name: coglinev3.ansible_python

- src: coglinev3.ansible_common
  version: master
  name: coglinev3.ansible_common
