---
- name: Converge
  hosts: all
  tasks:
    - name: "Include coglinev3.ansible_common"
      ansible.builtin.include_role:
        name: "coglinev3.ansible_common"
      vars:
        essential_packages:
          - git
        common_packages: []
    - name: "Include coglinev3.dotfiles"
      ansible.builtin.include_role:
        name: "coglinev3.dotfiles"
      vars:
        dotfiles_repo: "https://gitlab.com/cogline.v3/dotfiles.git"
        dotfiles_repo_version: master
        dotfiles_repo_local_destination: "~/.dotfiles"
        dotfiles_home: "~"
        dotfiles_files:
          - .bash_aliases
          - .bash_profile
          - .bash_prompt
          - .bashrc
          - .dircolors
          - .vim
          - .vimrc
          - .ssh/rc
