---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_REGISTRY:-docker.io}/${MOLECULE_NAMESPACE:-library}/${MOLECULE_DISTRO:-alpine}:${MOLECULE_DISTRO_VERSION:-3.20}
    pre_build_image: true
    command: tail -f /dev/null
provisioner:
  name: ansible
  log: false
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
